### ISSUE TITLE
model: markers on lines

### ISSUE THREAD

**Issue by mtbc** [openmicroscopy/design#18]
The OME-XML schema at http://www.openmicroscopy.org/Schemas/Documentation/Generated/OME-2015-01/ROI_xsd.html has `markerStart` and `markerEnd` properties on lines. These are absent among OMERO's model objects but are clearly anticipated by https://github.com/openmicroscopy/openmicroscopy/blob/037f0caf/components/model/resources/mappings/roi.ome.xml#L70.

Should String-based `markerStart` and `markerEnd` properties be added to OMERO's `Line` and `Polyline`? Perhaps some other change would be better to bring the two schemas into line?

**Comment by joshmoore** [comment]
Not having an alternative proposal, I would think we unify by adding the markers to OMERO.

**Comment by will-moore** [comment]
Enumerations for MarkerStart and MarkerEnd are 
 - Arrow
 - Circle
 - Square

Any idea's how a Circle and Square are displayed on the end of a line? E.g are they centred at the x,y coordinate, or fit inside it (like the Arrow does in OMERO.figure)?

![screen shot 2016-02-24 at 09 42 14](https://cloud.githubusercontent.com/assets/900055/13281329/28af40ea-dadb-11e5-9d3c-9fd7a71ed666.png)

Do they have a fixed size?
In OMERO.figure, I try to make a suitable-sized Arrow based on the line width, so maybe the same approach would apply to Circle and Square?
Do we even have any need for Circle and Square? Maybe we should only support Arrow?

**Comment by joshmoore** [comment]
![screen shot 2016-02-25 at 11 51 21](https://cloud.githubusercontent.com/assets/88113/13317587/312af77e-dbb6-11e5-8bb8-09de81d2a446.png)

**Comment by mtbc** [comment]
The current plan is to add `markerStart` and `markerEnd` to OMERO but to restrict OME-XML `Marker` to simply `Arrow` for the meantime.

**Comment by mtbc** [comment]
Fixed by https://github.com/openmicroscopy/bioformats/issues/2286 in https://github.com/openmicroscopy/bioformats/pull/2286/commits/a84850bab3d731a555cbb6f4441cc616e9a62b50 and by https://github.com/openmicroscopy/openmicroscopy/issues/4533 in https://github.com/openmicroscopy/openmicroscopy/pull/4533/commits/f1073105de8eaf937a16ac2d93f8041562e8963f.
