### ISSUE TITLE
ROI: Folders - Mockups - Measuring Tool - Display Folders + Filter Folders

### ISSUE THREAD

**Issue by gusferguson** [openmicroscopy/design#21]
As suggested by @will-moore, the display of folders in the Measurement Tool > Management tab could be determined using a menu similar to the Group Display menu in the main window. Along with the filtering suggested by @mtbc, this would help to handle late numbers of ROI folders.

As discussed 16-02-17, here are some mockups of what this might look like - albeit with modest numbers of ROI Folders.

The Display Folders drop down and Filter Folders text box would go above the main panel:

Suggest:
- the default display of ROI Folders should be only those folders that contain - or their children contain - ROIs on the current image
- this would probably satisfy most interactions apart from when new ROIs are being added or ROIs/ROI Folders are being organised/managed.

![01 step 3 - display and filter](https://cloud.githubusercontent.com/assets/1552703/13141713/ab5541b6-d630-11e5-9f77-cec949219ef3.png)

It would probably be useful to include a “Show All Folders” checkbox here so any filtering or selection can be toggled off  with a single click.

![02 step 4 - display and filter show all](https://cloud.githubusercontent.com/assets/1552703/13141824/570b991a-d631-11e5-8222-79a27845fce4.png)

Even with a modest number of ROI Folders, an un-nested list appears impractical - even with tooltips to show parents.

![03 step 4 - display dd tooltip](https://cloud.githubusercontent.com/assets/1552703/13141723/b9299ce2-d630-11e5-8135-e9c5a8a087a8.png)

Nesting makes more sense.

![05 step 4 - display dd nested 1](https://cloud.githubusercontent.com/assets/1552703/13141733/c1a799a0-d630-11e5-9ce0-08e7d0d2a94e.png)

In keeping with the Display Groups you could have a “Show All” at the top - either as well as or replacing the other Show All checkbox.

![06 step 4 - display dd nested 1 all](https://cloud.githubusercontent.com/assets/1552703/13141737/c9170eb4-d630-11e5-9362-198ff3e9b768.png)

Subfolders would be shown on mouse-over - selected:

![07 step 4 - display dd nested 2](https://cloud.githubusercontent.com/assets/1552703/13141744/cfa01910-d630-11e5-8880-b8c27ec51f82.png)

Subfolders shown on mouse-over - unselected:

![08 step 4 - display dd nested 3](https://cloud.githubusercontent.com/assets/1552703/13141749/d735997a-d630-11e5-82a0-e7edab26a282.png)

**Comment by pwalczysko** [comment]
I think it would be good to remark here explicitly: 
  - every newly created folder in this UI is immediately and automatically put onto display

**Comment by dominikl** [comment]
RE "Show All" within the popup menu: Would it make sense to call it "Select/Deselect All" in order to differentiate it from the "Show all Folders" checkbox in the toolbar. And, should sub menus also have a "Select/Deselect All" menu item?

**Comment by pwalczysko** [comment]
> Would it make sense to call it "Select All" ....?

Makes sense to me.

**Comment by gusferguson** [comment]
Sorry yes - it should be "Select All".

**Comment by will-moore** [comment]
What's the difference between "Show All" and "Select All"? Do they do the same thing? Why do you need them both?
I guess I still don't really understand why you'd want to Show All anyway?
What's the use-case / workflow?

**Comment by dominikl** [comment]
I thought you could have the "Show All Folders" checkbox in the toolbar, which overrides the filtering and just shows all folders when ticked (but it doesn't change/reset your filtering options). And in the filter popup menu you could have a "Select All" checkbox which resets the filtering by selecting or deselection all items in the popup menu.

**Comment by gusferguson** [comment]
@dominikl - I agree - that is how I think it should be.

**Comment by sbesson** [comment]
Briefly discuss with @dominikl, this first proposal in this issue, i.e. showing only "used" folders (Folders containing ROIs linked to the current Image) as the default certainly makes sense to me and covers most of the use cases I can think of when using the measurement tool (cf https://github.com/openmicroscopy/design/issues/21#issuecomment-196745967).

**Comment by dominikl** [comment]
I'd mark this as **Done**, fully implemented.
