### ISSUE TITLE
ROI: Folders - Measurement Tool - Step 4 

### ISSUE THREAD

**Issue by dominikl** [openmicroscopy/design#30]
Tasks which still have to be implemented (extracted from the brain storming design issues #11, #14 and  #15 and [Trello - ROI Folders Insight Bugs](https://trello.com/c/XUI38KAp/27-roi-folders-insight-bugs)):
- Delete Folder action: No warning/selection dialog for now. Subfolders will become top level folders. ROIs will be orphaned. **Done** (https://github.com/openmicroscopy/openmicroscopy/pull/4567)
- Folder Id, name, description (editable) in Inspector Tab **Done** (but not editable, "breadcrumb style" instead, needs further discussion)
- Folder path (breadcrumb style) in Results Tab - **Done** https://github.com/openmicroscopy/openmicroscopy/pull/4567
- Create new folder, when ROI is selected. Selected ROI should be added to new folder automatically **Done** (https://github.com/openmicroscopy/openmicroscopy/pull/4567)
- Performance problems for "Add ROIs to Folder" action have to be sorted out. **Done** (https://github.com/openmicroscopy/openmicroscopy/pull/4556)
- RFE: Trim folder names to fit into column space (like Project/Datasets name in left hand side tree) - This is really ugly to implement, propose to **postpone** for now.
- No "Move/Copy/Remove to Folder" popup menu actions with folder submenus, instead keep current "Add/Remove to Folder" actions followed by selection dialog. **Done** (it's the current state)
- Remove tooltips from ROI table. **Done**
- Right-click menu does not appear when multiselection of ROIs IN THE IMAGE (not in the ROI tool) is right-clicked (not "regions" specific, **separate PR**, candidate for develop rebase)

**Comment by pwalczysko** [comment]
I do not see here any tooltips design. Atm the tooltips show something else than what the mockups suggest.

**Comment by dominikl** [comment]
What should the tooltip show? The mockup says the folder path (breadcrumb style), but back then a flat hierarchy was assumed. Now we have the full hierarchy in the table, so why should the tooltip display something, what the user directly sees anyway? I'd suggest to remove the tooltip, as it doesn't work properly on the roi table (sometimes pops up, sometimes not; sometimes gets "stuck" somewhere, etc.), I think that's an issue of the underlying JXTreeTable.

**Comment by gusferguson** [comment]
@dominikl - I agree - no need for tooltips.

**Comment by pwalczysko** [comment]
Fine by me Re tooltips.

**Comment by dominikl** [comment]
Moved all outstanding issues to [Trello card: ROI Folders Insight Bugs/RFEs ](https://trello.com/c/XUI38KAp/27-roi-folders-insight-bugs).

**Comment by sbesson** [comment]
Thanks @dominikl. Closing this as listed steps should have been covered as part of https://github.com/openmicroscopy/openmicroscopy/releases/tag/v5.3.0-m2.
