### ISSUE TITLE
viewer-ng rename

### ISSUE THREAD

**Issue by will-moore** [openmicroscopy/design#63]
Before @waxenegger's [viewer-ng](https://github.com/waxenegger/viewer-ng) goes more public, we have discussed re-naming it.

Suggestions please!

NB: all web apps are now prefixed with 'omero-' E.g. [omero-figure](https://github.com/ome/omero-figure).
Also, the name will mostly show up to Users in web urls and maybe the viewer page title. Also in the 'Open with' dialog, although the label used for this can be anything: It doesn't have to be the same as the app name.

A few suggestions to get the discussion started:

 - omero-eye
 - omero-light
 - omero-focus
 - omero-zoom
 - omero-stage
 - omero-lens
 - omero-prism

**Comment by joshmoore** [comment]
* minor 👎 for zoom & stage or things that may otherwise show up in URLs
 * lens may conflict with elife
 * perhaps `phase`?
 * or something nice & German to go along with "blitz" like `licht`

**Comment by hflynn** [comment]
I think zoom would likely confuse all of us!

**Comment by jburel** [comment]
@pwalczysko was heading for "birds of prey"!!

**Comment by hflynn** [comment]
;) omero-kestrel ?

**Comment by pwalczysko** [comment]
OMERO.albatros

**Comment by pwalczysko** [comment]
OMERO.rishi  - see https://en.wikipedia.org/wiki/Rishi ``Post-Vedic tradition of Hinduism regards the Rishis (or Ruesi in Laos and Thailand) as "seers" ...``
Also would point out all the wisdom enshrined in the code... :)

**Comment by joshmoore** [comment]
:smile: Nice. E. suggests `OMERO.discovery`

**Comment by jburel** [comment]
@pwalczysko: only if the "options" come back to the lunch menu :-)

**Comment by hflynn** [comment]
I hope it's not going to be an albatross!

**Comment by waxenegger** [comment]
@joshmoore or something nice & German to go along with "blitz" like licht

Donner, Hagel, Unwetterschaden, Sturmversicherung, ... I know, I know ... I'm not being helpful here :grin:

**Comment by joshmoore** [comment]
OMERO.sturm (followed by OMERO.drang)

**Comment by manics** [comment]
OMERO.soar

**Comment by aleksandra-tarkowska** [comment]
as insight became legacy maybe just call OMERO.sight

**Comment by hflynn** [comment]
sight is likely to get confusing too even if insight is legacy, I think. OMERO.soar does have the advantage that it's not going to return anything else when searching the docs!

**Comment by bramalingam** [comment]
omero.inwebsight

**Comment by gusferguson** [comment]
OMERO.view
OMERO.viewer
OMERO.webview
OMERO.webviewer

**Comment by will-moore** [comment]
OMERO.vision?

I would prefer not to have web in the name. E.g. renaming of webfigure -> figure. In future everything will be web so the prefix is not needed.

**Comment by hflynn** [comment]
I like OMERO.vision - it's clear and has the advantage over viewer that it won't return loads of stuff when searching the docs.

**Comment by jburel** [comment]
few suggestions during today's meeting: OMERO.imageviewer, OMERO.iv

maybe OMERO.iviewer could be an happy medium

**Comment by gusferguson** [comment]
iviewer - very trendy!

**Comment by jburel** [comment]
I will probably rename the app while @waxenegger is travelling this weekend
and move the repo
so any objection to iviewer?

**Comment by will-moore** [comment]
I'm happy with OMERO.iviewer.

**Comment by jburel** [comment]
migrated to https://github.com/ome/omero-iviewer
