### ISSUE TITLE
iviewer multiple viewers

### ISSUE THREAD

**Issue by will-moore** [openmicroscopy/design#79]
Current prototype is @waxenegger's https://github.com/waxenegger/omero-iviewer/tree/mdi 

Main concerns:
 - Buttons on the viewer canvas seem to take up a more significant portion of space when viewers are smaller. Need to hide these by default in multi-view mode. Show them with click on 'settings' button?
 - Hiding other controls in the frame (e.g. Z/T controls & labels) is probably not worth it, since we don't save much space and it's confusing to users for some controls to disappear. Possible exception is the time-stamp label which could be hidden in multi-view mode.
 - When in "Multiviewer" mode, single clicks on thumbnails current open a new viewer. Not possible to "browse" through the thumbnails with a single click on each as you can in single viewer mode. I think that we should probably not have 2 modes, but multiple viewers can always be opened by double-clicking on thumbnails. Various text editors (Sublime & Visual Studio Code at least) operate something like this with multiple tabs. More details to follow...
 - Synchronisation of viewers - This needs to be bi-directional and is probably simplest to manage it via "groups" like Icy, since using image names won't work (duplicate viewers of same image). However, each group could be configured to sync Z/T and/or View (zoom, pan, rotation) and/or Channels.

Current screenshot....

<img width="1375" alt="screen shot 2017-10-04 at 14 59 38" src="https://user-images.githubusercontent.com/900055/31179752-ba517f0a-a914-11e7-98fd-fd46388f501e.png">

cc @jburel

**Comment by will-moore** [comment]
This proposal has some investigations of hiding controls in viewer frames: The top-left viewer has minimal controls, the bottom-left one ONLY has the timestamp label hidden, with the frame made a few pixels thinner. Other 2 viewers on the right have the current size of frame (bit thicker).

The currently active frame is a darker blue and the inactive ones are a lighter shade.

The viewers on the left are sync'd in Group 1, which syncs Z & T.
The viewers on the right are sync'd in Group 2 which syncs Z & T, View (zoom, pan & rotation) and Channels.
Checking/unchecking the sync checkboxes in either of the viewers on the left (group 1) will update both viewers. E.g. checking "Channels" in the top-left viewer will mean that "Channels" will also become checked in the bottom-left viewer.

This uses quite a bit of the frame space for sync'ing controls. Do we need to keep more space free for other features? The "cog" button on the right hides & shows the canvas zoom controls.
  
![multi-viewers](https://user-images.githubusercontent.com/900055/31179938-2c064fd6-a915-11e7-94ff-a00dc4ee0179.png)

**Comment by will-moore** [comment]
Multiple viewers opened by double-clicking on thumbnails....
I suggest we shouldn't need to toggle into "multi-viewer mode" but can always open multiple viewers by double clicking.
The exact details of how this proposal works are still to be worked out / discussed but 2 principles:

 - Double-clicking on a thumbnail opens the image in multi-view mode.
 - Sequential single clicks on thumbnails open each image in the same viewer (don't open a new viewer for each)

In the following sequence, we start with only a single viewer open. This behaves in all ways as the current iviewer does.

![multi-viewers-1](https://user-images.githubusercontent.com/900055/31182142-f918b16c-a91a-11e7-9005-f41767f248b4.png)

Now we double-click on another thumbnail. This opens that image in a new viewer, alongside the existing viewer.

![multi-viewers-2](https://user-images.githubusercontent.com/900055/31182187-1708e1ec-a91b-11e7-969b-609a8dad6c10.png)

(The same would also happen if we double-clicked on the currently-selected thumbnail - in that case we'd have both viewers showing the same image)

Now, we continue & click on another thumbnail with a single click. This *does* open a new viewer simply because the 2 existing viewers are active / pinned. 

![multi-viewers-3](https://user-images.githubusercontent.com/900055/31182419-bae6827e-a91b-11e7-8e35-ae2db918fb97.png)


The newest viewer is "temporary", so that subsequent clicks on other thumbnails will continue to open images in this "temporary" / "unpinned" viewer:

![multi-viewers-4](https://user-images.githubusercontent.com/900055/31182467-d7cacfc6-a91b-11e7-820b-a69f1176938c.png)

If we want to keep that viewer open while browsing more images in a new viewer, we could "pin" that viewer open using the pin icon in the top-right of the frame. Then it would show the X like the other viewers and subsequent single clicks on thumbnails would open a new "temporary" window.

Also it's possible that starting to browse Z/T or adjust settings etc on the "temporary" viewer would cause it to become "pinned" and would stay open. Certainly drawing ROIs would cause the "temporary" viewer to become pinned open.
We'd only ever need a single "temporary" viewer.

Minor/undecided details:
- If no temporary viewer is open and a thumbnail for a currently open image is single-clicked, simply select the corresponding open viewer? If the temporary window IS open, show the image in there.
 - If the temporary viewer is showing image 1 and we double-click thumbnail of that image, this could cause the temporary viewer to become pinned OR it could open that image in a new pinned viewer?
 - Can the temporary viewer be closed directly? In the screenshots above it would need to be pinned before the X appears to close it. Could show the "pin" icon alongside the X icon on temporary viewer.
 - When all but one images are closed, we return to single-viewer layout (same as current behaviour).

**Comment by waxenegger** [comment]
@will-moore: isn't there a certain redundancy in the lock group and the checkboxes?

I have never used icy before and I make the bold claim that others haven't either and the implicit group  meanings in terms of locking are not really transparent. In fact, I would have only guessed at best if you hadn't mentioned it. What if we use the group as just a mere group/set that denotes the images that are to be linked and the check boxes denote the actual action to synchronize. 

With both behaviors applied there is not only redundancy but I override hell/ui adjustment need. Because if I use group 1 for example and then uncheck z/t and view I have essentially no sync, right?

**Comment by will-moore** [comment]
Discussed a few issues with @bramalingam and @pwalczysko. Quite a bit of discussion was inconclusive, but a few things came out...:

 - Petr said that Icy is quite well used in many places we've visited, so although we can't assume users will know about it (or ever used the sync feature) it certainly could be familiar to some. So, where there's not a reason for making things look different, we might as well make it look similar.
I managed to find and understand the 'lock/sync' feature in Icy without instruction or docs so I think we should be able to make a feature that is equally usable.

 - Balaji wanted to be able to see the image name on the frame of each viewer. I'm not sure if I convinced him that the amount of space this would take up on screen might not be worth it?

 - Current iviewer behaviour is nice that even when Z & T are sync'd, you can change T, T syncs with  the other image(s) but Z doesn't unless you actually change it. This means that when Z/T are combined into a single sync option (as in screenshots above) you can *still* have 2 images at different Z, moving through T together.

- Balaji seemed in general agreement about not having a different "multi-viewer mode" and the proposed double-click behaviour for opening multiple viewers seemed reasonable.

- There could be a use-case for keeping timestamp visible at the bottom of each frame, for comparing event times for several viewers. So let's not hide that as suggested above.

- We should probably hard-code a fixed number of sync groups, e.g. 3 since there is a use-case for possibly 2 or 3 images with multiple viewers each (one per channel), so we'd need a group for each image set. @waxenegger You are right, if you uncheck z/t and c and view then you have no sync. Probably we start of with all of these checked, so the user wouldn't enter the "all unchecked" state unless deliberately. It's nice to be able to toggle all the checkboxes as you work, so there may be times when you temporarily do uncheck them all. No reason for us to prevent this.

Any additional comments @pwalczysko @bramalingam?

**Comment by will-moore** [comment]
The sync checkboxes (Z/T, View & Channel) currently mean that this space can't really be used for any other toolbar button we might want to add in future. Although there might be space available if we use "View", "Z/T" and "Ch" labels, it's not very nice to push other buttons to the right when we switch to a sync group. I guess we could add a small number of buttons to the right (next to the 'show toolbar' cog button).

Another area that @bramalingam and I discussed yesterday was the similarity in layout & features between iviewer and figure. We agreed that we would always need 2 separate apps (even if iviewer implements a lot of figure features) but that you could exchange data / layout between the apps, possibly in the form of a figure JSON file (maybe modified/simplified). This might allow you to create a layout of viewers in iviewer, save it as a JSON file to be opened later in iviewer or figure.

**Comment by jburel** [comment]
we will definitely need to app. discussing with people and listening to talks here, more ideas for figure...
improving the communication between the 2 is essential

**Comment by bramalingam** [comment]
Just a small point to add, we did discuss the options for layout management in the multi-window feature (similar to what we have in figure)

**Comment by bramalingam** [comment]
Instead of having a lock feature, I would still be inclined to following the multi select feature like figure to manage groups of images (if its possible). We already have groups in OMERO, adding another concept of groups in this windows could be potentially confusing.

**Comment by jburel** [comment]
@bramalingam will having the ability to move each window around not be enough? or were you thinking of having for example a "grid" control to make sure the windows are displayed in a grid.

**Comment by will-moore** [comment]
@jburel - @bramalingam was referring to the "grid" button in OMERO.figure that lays out the viewers in a grid. Handy to arrange viewers so that they maximise available space and don't overlap etc.

@bramalingam I think we're not going to support multi-selection of viewers in iviewer like we do in figure since the workflow is a bit different. E.g. in iviewer you can "sync" 2 viewers for a longer period of time, moving back and forth between them (changing the selected image etc) without losing the "locking" of the images together. In figure where sync depends on selection, it is much more transient. Also, supporting "merge" of multiple selected images into the right panels (as we do in figure) is not supported in iviewer and would be pretty hard to do.

**Comment by pwalczysko** [comment]
I like the idea of @will-moore https://github.com/openmicroscopy/design/issues/79#issuecomment-334186297 concerinng the concept of double-click for opening images in multi-view,  I think leaving the syncing and buttons on the viewing pannels as they are now and implementing this concept would be a good idea.
The only point I am not sure about in https://github.com/openmicroscopy/design/issues/79#issuecomment-334186297 is the "pinning" button. 
  - Maybe we could simplify the concept by simply saying "single-click is browsing in one window" and "double click opens multi-view mode". 
  - When there is a single click on another image when being in multi-view mode, start using the active window for viewing of the singly-clicked image. 
  - If the user closes all windows in the multi-view mode, revert back to the image in single-view mode which was opened when iviewer was first opened (actually matches present behaviour).

This simplification gets rid of the "pinning" behaviour, which I find is very hard to discover for the user.

**Comment by will-moore** [comment]
Since we have dealt with most issues here, moving remaining discussion to https://github.com/openmicroscopy/design/issues/81
