### ISSUE TITLE
iviewer multiviewers on double-click

### ISSUE THREAD

**Issue by will-moore** [openmicroscopy/design#81]
This continues the design from https://github.com/openmicroscopy/design/issues/79
focusing only on the opening of viewers with double-click.

As discussed with @pwalczysko (see his last comment https://github.com/openmicroscopy/design/issues/79#issuecomment-353084228) we can simplify the desired behaviour (no 'pinning', 'temporary windows' etc):

 - No single vv multi-viewer mode.
 - When a single viewer is open, behaviour is same as current behaviour.
 - Single-clicking on a thumbnail opens the image in the currently-active viewer (does nothing if current viewer is already showing that image).
 - Double-click on a thumbnail will open the image in a NEW viewer panel.
 - When closing viewers, when only a single one is open it reverts to filling the space (as current behaviour).

cc @waxenegger @jburel

**Comment by waxenegger** [comment]
@will-moore @jburel distinction between single and double clicks in terms of event handling is a undetermined nuisance. In essence a double click is very likely to cause a single click event first, after that a double click event is fired. According to some sources out there some browsers could even do it the other way round. But even if we assume it's the former which is the behavior I get one needs a timer solution to handle that. Hacky it best. Here is what the jquery doc has to say: https://api.jquery.com/dblclick/ (but it's really something that is problematic based on generic event handling, not jquery, I wouldn't even be using jquery in that case)

**Comment by jburel** [comment]
Another option could be to drag a thumbnail from left panel to centre panel
to open in mulitview
